---
- hosts: dev 
  become: True
  tasks:
    - name: Install packages
      yum:
        name: "httpd"
        state: "present"
  notify:
    - restart httpd
    - name: Start Apache server
      service:
        name: httpd
        state: started
        enabled: True
     - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
  handlers:
    - name: restart httpd
      service: 
      name: httpd 
      state: restarted
      enabled: True
   
...
      
