---
- hosts: dev 
  become: True
  tasks:
    - name: Install packages
      yum:
        name: "httpd"
        state: "present"
    - name: Start Apache server
      service:
        name: httpd
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
       notify:
    - Restart apache

  - name: Ensure apache is running
      name: httpd
      state: started

  handlers:
    - name: Restart apache
        name: httpd
        state: restarted
