---
- hosts: dev 
  become: True
  tasks:
    - name: Install packages
      yum:
        name: "httpd"
        state: "present"
    - name: Start Apache server
      service:
        name: httpd
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
        notify: restart service
        handlers:
    - name: restart Apache server
      service:
        name: httpd
         state: restarted
        enabled: yes
        register:restart
        
...
