---
- hosts: dev 
  become: True
  tasks:
  - name: "httpd software installation"
    package:
      name: "httpd"
      state: present


  - name: "Creating web pages"
    copy:
      src: "index.html"
          dest: "/var/www/html/index.html"
    notify: restart service


  handlers:
  - name: restart service
    service:
	  name: "httpd"
	  state: restarted
	  enabled: yes
    register: restart
  - debug:
      var: restart.stdout
  
